### PR TITLE
Restrict aiomcache to versions < 0.7.0

### PR DESCRIPTION
**Pull request by minorgod**
aiomcache version 0.7.0 breaks aiocache[memcached] in Python 3.8 and probably others:
When trying to create the default cache, aiocache throws:
```
TypeError: __init__() got an unexpected keyword argument 'loop'
```
Restricting aimcache lib < 0.7.0 fixes the issue. 

## Related issue number

https://github.com/aio-libs/aiocache/issues/554

### CODE REVIEW

**Comment by Dreamsorcerer** [comment]
Would be better to update the code to be compatible, and drop any deprecated loop parameters so everything continues working on Python 3.10+.

**Comment by Dreamsorcerer** [comment]
Latest code works, so this isn't relevant anymore.
